# You can change plugin language by changing below. We support English or Japanese.
locale: English

# コマンドのパーミッションを0から100の間で設定できます。
commands:
  help: 0
  lang: 0
  punish: 70
  search: 50
  rank: 0
  userinfo: 70