# You can change plugin language by changing below. We support English or Japanese.
locale: English

# コマンドのパーミッションを0から100の間で設定できます。
commands:
  shelp: 0
  slang: 0
  spunish: 70
  ssearch: 50
  server-utility: 100
  test: 0
  srank: 0