main: com.onigori.serverutility.bootstrap.PluginBootstrap
name: Server-Utility
version: 1.0
commands:
  spunish:
    aliases: [punish]
  slang:
    aliases: [lang]
  shelp:
    aliases: [help]
  ssearch:
    aliases: [search]
  server-utility:
    aliases: [sutil, su]
  test: