main: com.onigori.serverutility.bootstrap.PluginBootstrap
name: Server-Utility
author: Onigori_Rage
version: 0.8.1
commands:
  punish:
  lang:
  help:
    aliases: [shelp]
  search:
  rank:
  userinfo: